# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Isctl < Formula
  desc ""
  homepage ""
  version "0.1.14"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cgascoig/isctl/releases/download/v0.1.14/isctl_0.1.14_Darwin_x86_64.zip"
      sha256 "b557c2f53490b22419774dedf8595665563798fb7eae5ec72d1cd00ec2d7a9ab"

      def install
        bin.install "isctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cgascoig/isctl/releases/download/v0.1.14/isctl_0.1.14_Darwin_arm64.zip"
      sha256 "f3583b00743f0e25a69b71ad365a91b41269d715ec2a8d53d1a09abd9dee7770"

      def install
        bin.install "isctl"
      end
    end
  end
end
