# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Isctl < Formula
  desc ""
  homepage ""
  version "0.1.20"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cgascoig/isctl/releases/download/v0.1.20/isctl_0.1.20_Darwin_x86_64.zip"
      sha256 "647812915503a9c2cf18de5a8465590552404f30c5bf2b843e9adc97a369a529"

      def install
        bin.install "isctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cgascoig/isctl/releases/download/v0.1.20/isctl_0.1.20_Darwin_arm64.zip"
      sha256 "945caf12bed09e9916fb065ea746405bbec86d3d05b6bb8c40b231c2113508ce"

      def install
        bin.install "isctl"
      end
    end
  end
end
