# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Isctl < Formula
  desc ""
  homepage ""
  version "0.1.25"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cgascoig/isctl/releases/download/v0.1.25/isctl_0.1.25_Darwin_x86_64.zip"
      sha256 "07d652ef254af8956553aaac1ac9a1f8667e5ff7888d680a109bddb1e664b3f9"

      def install
        bin.install "isctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cgascoig/isctl/releases/download/v0.1.25/isctl_0.1.25_Darwin_arm64.zip"
      sha256 "4d5f6066476c899727adb88b76e76cbf4b7004825576cd84dcdb83bba5409c50"

      def install
        bin.install "isctl"
      end
    end
  end
end
